# Pi 5 (cerebellum)
ros_distro = "jazzy"
domain_id = 42
rmw = "rmw_cyclonedds_cpp"

services = [
  "ros",
  "workspace",
  "foot",      # Create base (libcreate fork)
  "imu",       # mpu6050
#  "camera",    # usb_cam
 "eye_kinect", # Kinect RGB-D (freenect, publishes /camera/*)
#  "vision",    # object detection and tracking
  "mic",       # alsa setup only, optional ros audio later
  "gps",       # u-blox7 via nmea_navsat_driver
  "robot",     # robot_state_publisher from URDF
  "nav",       # nav2 + slam_toolbox
  "voice"     # piper tts voice service
]
