services:
  psyche:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/snd:/dev/snd"
      - "/dev/gpiochip0:/dev/gpiochip0"
      - "/dev/gpiochip1:/dev/gpiochip1"
    volumes:
      - ./memory:/psyche/memory
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  memory:
    image: crazymax/dokuwiki:latest
    ports:
      - "9000:8000"
    volumes:
      - ./memory:/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - MEMORY_LIMIT=256M
      - UPLOAD_MAX_SIZE=16M
