services:
  psyche:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ROS_REPO=osrf/ros:iron-desktop
    network_mode: host
    volumes:
      - ./memory:/psyche/memory
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  tts:
    image: ghcr.io/coqui-ai/tts-cpu
    ports:
      "5002:5002"

  memory:
    image: crazymax/dokuwiki:latest
    ports:
      - "9000:8000"
    volumes:
      - ./memory:/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - MEMORY_LIMIT=256M
      - UPLOAD_MAX_SIZE=16M
