services:
  psyche:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ROS_REPO=osrf/ros:iron-desktop
    network_mode: host
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  tts:
    image: ghcr.io/coqui-ai/tts
    ports:
      - "5002:5002"
    entrypoint: python3
    command: ["TTS/server/server.py", "--model_name", "tts_models/en/vctk/vits"]

    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
  
  memory:
    image: neo4j:community
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./memory:/data
    environment:
      - NEO4J_AUTH=none

