services:
  psyche:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ROS_REPO=arm64v8/ros:iron
    network_mode: host
    ports:
      - "8200:8200"
    devices:
    - "/dev/ttyUSB0:/dev/ttyUSB0"
    - "/dev/video0:/dev/video0"
    - "/dev/snd:/dev/snd"
    - "/dev/gpiochip0:/dev/gpiochip0"
    - "/dev/gpiochip1:/dev/gpiochip1"
    - "/dev/gpiochip0:/dev/gpiochip2"
    - "/dev/gpiochip1:/dev/gpiochip3"
    - "/dev/gpiochip0:/dev/gpiochip4"
    - "/dev/gpiochip1:/dev/gpiochip5"
