services:
  psyche:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ROS_REPO=arm64v8/ros:iron
    network_mode: host
    volumes:
      - "/psyche/src:/psyche/src"
    devices:
        - "/dev/ttyUSB0:/dev/ttyUSB0"
        - "/dev/video0:/dev/video0"
        - "/dev/gpiochip0:/dev/gpiochip0"
        - "/dev/gpiochip1:/dev/gpiochip1"
        - "/dev/gpiochip2:/dev/gpiochip2"
        - "/dev/gpiochip3:/dev/gpiochip3"
        - "/dev/gpiochip4:/dev/gpiochip4"
        - "/dev/gpiomem0:/dev/gpiomem0"
        - "/dev/gpiomem1:/dev/gpiomem1"
        - "/dev/gpiomem1:/dev/gpiomem2"
        - "/dev/gpiomem1:/dev/gpiomem3"
        - "/dev/gpiomem1:/dev/gpiomem4"
        - "/dev/snd/controlC0:/dev/snd/controlC0"
        - "/dev/snd/pcmC0D0p:/dev/snd/pcmC0D0p"
        - "/dev/snd/pcmC0D0c:/dev/snd/pcmC0D0c"
    environment:
      - ALSA_CARDS=0
