services:
  psyche:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ROS_REPO=arm64v8/ros:iron
    network_mode: host
    devices:
        - "/dev/ttyUSB0:/dev/ttyUSB0"
        - "/dev/video0:/dev/video0"
        - "/dev/gpiochip0:/dev/gpiochip0"
        - "/dev/gpiochip1:/dev/gpiochip1"
        - "/dev/gpiochip0:/dev/gpiochip2"
        - "/dev/gpiochip1:/dev/gpiochip3"
        - "/dev/gpiochip0:/dev/gpiochip4"
        - "/dev/gpiochip1:/dev/gpiochip5"
        - "/dev/snd/controlC1:/dev/snd/controlC0"
        - "/dev/snd/pcmC1D0p:/dev/snd/pcmC0D0p"
        - "/dev/snd/pcmC1D0c:/dev/snd/pcmC0D0c"
    environment:
      - ALSA_CARDS=0
