amcl:
  ros__parameters:
    use_map_topic: false
map_server:
  ros__parameters:
    yaml_filename: ""
bt_navigator:
  ros__parameters:
    default_nav_to_pose_bt_xml: "navigate_w_replanning_and_recovery.xml"
controller_server:
  ros__parameters:
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
planner_server:
  ros__parameters:
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
behavior_server:
  ros__parameters: {}
waypoint_follower:
  ros__parameters: {}
