slam_toolbox:
  ros__parameters:
    use_sim_time: false
    slam_toolbox:
      mode: mapping
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    map_update_interval: 2.0
    resolution: 0.05
    publish_tf: false
