[device]
id = "brainstem"
roles = ["robot", "bridge"]
hostname = "brainstem.local"

[layer1]
# Participate in the lowest layer (zenoh) as a lightweight client
mode = "client"
scouting = true
bridge_ros2dds = { enabled = false }

[layer2]
# Pico W does not run ROS 2
ros_distro = "none"

[layer3]
# No layer3 processes on the Pico W itself
nodes = []

[python]
requirements = ["zenoh-python>=0.11.0", "smbus2"]
