[device]
id = "ear"
roles = ["mic", "camera", "web"]
hostname = "ear.local"

[layer1]
mode = "peer"
scouting = true
seed_peers = ["tcp/forebrain.local:7447", "tcp/cerebellum.local:7447"]
bridge_ros2dds = { enabled = true }

[layer2]
ros_distro = "jazzy"
rmw = "rmw_cyclonedds_cpp"
domain_id = 42
namespace = "/ear"

[layer3]
nodes = [
]

[[layer3.nodes]]
name = "ublox_publisher"
type = "node"
package = "psyche_ublox_publisher"
executable = "ublox_publisher"
namespace = "/ear"

[hardware.gps]
type = "ublox7"
enabled = true
# Serial device path (provisioning may create a symlink in /dev/serial/by-id)
serial_port = "/dev/ttyUSB0"
baud = 9600
# Whether to use gpsd (true) or read NMEA directly in the node (false)
use_gpsd = true

[python]
requirements = ["rclpy", "opencv-python", "pynmea2", "pyserial"]