[device]
id = "ear"
roles = ["imu", "mic"]
hostname = "ear.local"

[layer1]
mode = "client"
scouting = true
bridge_ros2dds = { enabled = true }

[layer2]
ros_distro = "jazzy"
rmw = "rmw_cyclonedds_cpp"
domain_id = 42

[[layer3.nodes]]
name = "imu_mpu6050"
type = "direct"
package = "python3"
executable = "/home/runner/work/psyche/psyche/layer3/services/imu_mpu6050_node.py"
namespace = "/ear"
