[device]
id = "forebrain"
roles = ["forebrain", "router", "vision"]
hostname = "forebrain.local"

[layer1]
mode = "router"
scouting = true
listen_endpoints = ["tcp/0.0.0.0:7447"]
bridge_ros2dds = { enabled = true }

[layer2]
ros_distro = "jazzy"
rmw = "rmw_cyclonedds_cpp"
domain_id = 42

[[layer3.nodes]]
name = "image_proc"
type = "node"
package = "image_proc"
executable = "image_proc"
namespace = "/vision"

[layer3.services.web]
enabled = true
host = "0.0.0.0"
port = 8000
