#!/usr/bin/env bash
set -euo pipefail
. "$(dirname "$0")/_common.sh" 2>/dev/null || true

# voice.sh — Provision voice service (eSpeak) + ROS2 node and systemd launcher
# Features:
# - Subscribes to /voice/$HOSTNAME for text (std_msgs/String)
# - Queueing of utterances
# - Control via /voice/$HOSTNAME/cmd (std_msgs/String): interrupt|resume|abandon
#   and convenience topics /voice/$HOSTNAME/{interrupt,resume,abandon}
# - Uses espeak-ng with aplay for playback.

ROOT="/opt/psyched"
ETC_DIR="/etc/psyched"
PY_NODE_PATH="${ETC_DIR}/voice_node.py"
LAUNCH_PATH="${ETC_DIR}/voice.launch.sh"

ensure_deps() {
  export PSY_DEFER_APT=1
  # Core runtime dependencies for espeak-ng
  common_apt_install alsa-utils espeak-ng espeak-ng-data
}

write_default_config() {
    local config="/etc/default/psyched-voice"

    if [ ! -f "$config" ]; then
        sudo tee "$config" >/dev/null <<'CFG'
# Auto-generated by voice.sh provision
PSY_TTS_ENGINE=espeak
# Optional espeak-ng customisation examples:
# PSY_ESPEAK_VOICE=en+m7
# PSY_ESPEAK_RATE=170
# PSY_ESPEAK_PITCH=50
# PSY_ESPEAK_ARGS=--path=/usr/share/espeak-ng-data
CFG
    elif ! sudo grep -qE '^[[:space:]]*PSY_TTS_ENGINE=' "$config"; then
        printf '\nPSY_TTS_ENGINE=espeak\n' | sudo tee -a "$config" >/dev/null
    fi
}

install_node() {
  sudo mkdir -p "$ETC_DIR"
  if [ -f "${ROOT}/provision/services/voice_node.py" ]; then
    sudo install -m 0755 "${ROOT}/provision/services/voice_node.py" "$PY_NODE_PATH"
  else
    echo "[voice] ERROR: voice_node.py missing from repository; cannot install" >&2
    return 1
  fi

  sudo tee "$LAUNCH_PATH" >/dev/null <<'LAUNCH'
#!/usr/bin/env bash
set -e
set +u; source /opt/ros/${ROS_DISTRO:-jazzy}/setup.bash; set -u

if [ -f /etc/default/psyched-voice ]; then
  source /etc/default/psyched-voice
fi

export PSY_TTS_ENGINE="espeak"
unset PSY_PIPER_BIN
exec python3 /etc/psyched/voice_node.py
LAUNCH
  sudo chmod +x "$LAUNCH_PATH"
}

provision() {
    ensure_deps
    install_node
    write_default_config
    echo "[voice] Provisioned espeak-ng engine. Customise via PSY_ESPEAK_VOICE/PSY_ESPEAK_RATE/PSY_ESPEAK_PITCH."
    echo "[voice] provisioned. Use: sudo systemctl start psyched@voice.service"
}

case "${1:-provision}" in
  provision) provision ;;
  *) echo "unknown"; exit 1;;
esac
